site_name: Thinking-In-Minecraft
site_url: https://ex.com
site_description: Minecraft Design
site_author: Dreamtowards

repo_url: https://github.com/Dreamtowards/Thinking-In-Minecraft
edit_uri: ""

theme: readthedocs

pages:
    - 主頁: index.md
    - 目錄:
        - 第一章: index.md
        - 第一章1: index.md
        - 第一章2: index.md
        - 第一章3: index.md
        - 第一章4: intro.md
        - 第一章5: 
            - 第二章: index.md
            - 第二章2: index.md
        - 第一章7: conf.md
    
extra_css:
    - css/base.css
    - css/bootstarp-custom.min.css
    - css/style.css
    - css/highlight.css
    - css/admonition-fix.css
    
markdown_extensions:
    - admonition

docs_dir: 'docs'

#copyright: Copyright &copy; 2017 Dreamtowards
