site_name: Thinking-In-Minecraft
site_url: https://ex.com
site_description: Minecraft Design
site_author: Dreamtowards

repo_url: https://github.com/Dreamtowards/Thinking-In-Minecraft
edit_uri: ""

theme: mkdocs

pages:
    - 主頁: index.md
    - 目錄:
        - abc: a.md
    
extra_css:
    - css/extra.css

copyright: Copyright &copy; 2014

docs_dir: 'docs'

theme_dir: 'yeti'
